spring:
  datasource:
    url: jdbc:mysql://localhost:3306/local-test?useSSL=false&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
#    username: uhealth
#    password: uhealth123
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
