spring:
  datasource:
    url: jdbc:mysql://192.168.8.24:3306/test?useSSL=false&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
    username: uhealth
    password: uhealth123
  redis:
    host: 192.168.8.24
    port: 6379
    password: uhealth
  rabbitmq:
    host: 192.168.8.24
    port: 5672
    username: uhealth
    password: uhealth
    publisher-confirms: true
    virtual-host: /
