server:
  port: 8100
  context-path: /api

spring:
  application:
    name: single-demo-scaffold
  http:
    encoding:
      charset: utf-8
      force: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #监控统计用的filter:stat
    #日志用的filter:log4j
    #防御sql注入的filter:wall
    filters: stat,wall,log4j
    maxActive: 20
    initialSize: 5
    # 配置获取连接等待超时的时间
    maxWait: 60000
    minIdle: 1
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 校验SQL，Oracle配置 spring.datasource.validationQuery=SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  redis:
    pool:
      max-total: 1000
      max-idle: 10
      min-idle: 1
      max-wait-millis: 30000
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
    timeout: 1000

  devtools:
    restart:
      enabled: false
